// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9jfd8End8sLHwcOsrlLqt8S7j6K-zJ0M',
    appId: '1:39062784005:web:dbdb996a5cdedf1ea5b46c',
    messagingSenderId: '39062784005',
    projectId: 'notificationsapp-25689',
    authDomain: 'notificationsapp-25689.firebaseapp.com',
    storageBucket: 'notificationsapp-25689.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBorrz-f_4xOIPT10F9ACACKVuinURoofc',
    appId: '1:39062784005:android:0f753f58bf9a2708a5b46c',
    messagingSenderId: '39062784005',
    projectId: 'notificationsapp-25689',
    storageBucket: 'notificationsapp-25689.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk87f-lVMSpLr3HLL87K7X3gAh8oiU_TA',
    appId: '1:39062784005:ios:297ebaf7f6b58988a5b46c',
    messagingSenderId: '39062784005',
    projectId: 'notificationsapp-25689',
    storageBucket: 'notificationsapp-25689.appspot.com',
    iosBundleId: 'com.example.notificationPushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk87f-lVMSpLr3HLL87K7X3gAh8oiU_TA',
    appId: '1:39062784005:ios:297ebaf7f6b58988a5b46c',
    messagingSenderId: '39062784005',
    projectId: 'notificationsapp-25689',
    storageBucket: 'notificationsapp-25689.appspot.com',
    iosBundleId: 'com.example.notificationPushApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9jfd8End8sLHwcOsrlLqt8S7j6K-zJ0M',
    appId: '1:39062784005:web:6f10113daca5ca91a5b46c',
    messagingSenderId: '39062784005',
    projectId: 'notificationsapp-25689',
    authDomain: 'notificationsapp-25689.firebaseapp.com',
    storageBucket: 'notificationsapp-25689.appspot.com',
  );

}